### PR TITLE
BetterRoleDot, noDevtoolsWarn, noDmCallIdle

### PR DESCRIPTION
**Pull request by ImLvna**

### CODE REVIEW

**Comment by Cynosphere** [comment]
noDevtoolsWarn is redundant as its apart of Quiet Loggers (theres an option to only hide the devtools warning)

**Comment by NotNite** [comment]
- BetterRoleDot is blocked by [this PR](https://github.com/moonlight-mod/moonlight/pull/13).
- BetterRoleDot still features the [example Webpack modules](https://github.com/ImLvna/moonlight-extensions/blob/f5e8a1c98894a5925d3b41fcc45760c6bdb23ed0/src/betterRoleDot/index.tsx#L38-L64), please remove them.

**Comment by ImLvna** [comment]
> BetterRoleDot still features the [example Webpack modules](https://github.com/ImLvna/moonlight-extensions/blob/f5e8a1c98894a5925d3b41fcc45760c6bdb23ed0/src/betterRoleDot/index.tsx#L38-L64), please remove them.
fixed!

**Comment by ImLvna** [comment]
nvm im stupid lmao

**Comment by ImLvna** [comment]
added: noDmCallIdle

**Comment by NotNite** [comment]
It doesn't seem like your latest extension made it into the PR - can you make sure that's submitted?

**Comment by ImLvna** [comment]
whoops, forgot to push

**Review by NotNite — APPROVED** [review]
Your extensions emailing me made me think CI failed. :p

Also, note that your extension that uses `\i` will only work on develop until we do the next release.

**Pull request merged**
